In [16]:
import pandas as pd
import numpy as np

In [ ]:
# 1. 用三种不同的方法，创建以下Dataframe（保证columns和index一致，值不做要求）

# 结果Dataframe为：
#     four  one  three  two
# a     4    1      3    2
# b     5    2      4    3
# c     6    3      5    4
# d     7    4      6    5
# e     8    5      7    6

In [ ]:

data = [
    [4,1,3,2],
    [5,2,4,3],
    [6,3,5,4],
    [7,4,6,5],
    [8,5,7,6]
]
df = pd.DataFrame(data,index=["a","b","c","d","e"],columns=["four","one","three","two"])
df

In [ ]:
data = {
    "four":[4,5,6,7,8],
    "one":[1,2,3,4,5],
    "three":[3,4,5,6,7],
    "two":[2,3,4,5,6],
}
df = pd.DataFrame(data,index=["a","b","c","d","e"])
df

In [12]:
data = [
    {"four":4,"one":1,"three":3,"two":2},
    {"four":5,"one":2,"three":4,"two":3},
    {"four":6,"one":3,"three":5,"two":4},
    {"four":7,"one":4,"three":6,"two":5},
    {"four":8,"one":5,"three":7,"two":6},
]
df = pd.DataFrame(data,index=["a","b","c","d","e"])
df

   four  one  three  two
a     4    1      3    2
b     5    2      4    3
c     6    3      5    4
d     7    4      6    5
e     8    5      7    6

In [14]:
data = {
    'four' : pd.Series([4,5,6,7,8], index=["a","b","c","d","e"]),
    'one' : pd.Series([1,2,3,4,5], index=["a","b","c","d","e"]),
    'three' : pd.Series([3,4,5,6,7], index=["a","b","c","d","e"]),
    'two' : pd.Series([2,3,4,5,6], index=["a","b","c","d","e"]),
  }
df = pd.DataFrame(data)
df

   four  one  three  two
a     4    1      3    2
b     5    2      4    3
c     6    3      5    4
d     7    4      6    5
e     8    5      7    6

In [21]:
# 2. 如图创建Dataframe(4*4，值为0-100的随机数)，通过索引得到以下值
#     ① 索引得到b，c列的所有值
#     ② 索引得到第三第四行的数据
#     ③ 按顺序索引得到two，one行的值
#     ④ 索引得到大于50的值
#           a          b          c          d
# one    60.936882  34.198569  86.933961  63.217850
# two    93.910622   8.843498  12.482240  35.940462
# three  11.350391  40.704308  50.524502   5.215897
# four    5.777448  75.515444  96.847913  57.683561

In [25]:
# 创建列表
# 这里使用了np.reshape函数把一维数组变为二维
df = pd.DataFrame(np.reshape(np.random.rand(16)*100,(4,4)) ,index=["one","two","three","four"],columns=["a","b","c","d"])
df

               a          b          c          d
one    63.805662  11.297014  34.377420  86.509633
two    29.753325  52.779439  76.926601  48.403465
three  71.488561  91.026485  77.638512  27.286880
four   81.732061   4.492647  93.702347  37.688954

In [32]:
# 索引得到b,c列的值
b = df["b"].values
print(b,type(b))
c = df["c"]
print(c,type(c))

[11.29701367 52.77943877 91.0264853   4.4926475 ] <class 'numpy.ndarray'>
one      34.377420
two      76.926601
three    77.638512
four     93.702347
Name: c, dtype: float64 <class 'pandas.core.series.Series'>

In [34]:
# 索引得到第三第四行的数据
# loc函数和iloc函数参数为[行,列]
# print(df.loc['two'])
print(df.iloc[2],type(df.iloc[2]))
print(df.iloc[3],type(df.iloc[3]))

a    71.488561
b    91.026485
c    77.638512
d    27.286880
Name: three, dtype: float64 <class 'pandas.core.series.Series'>
a    81.732061
b     4.492647
c    93.702347
d    37.688954
Name: four, dtype: float64 <class 'pandas.core.series.Series'>

In [37]:
#  索引得到大于50的值
result = df[df>50]
print(result,type(result))

               a          b          c          d
one    63.805662        NaN        NaN  86.509633
two          NaN  52.779439  76.926601        NaN
three  71.488561  91.026485  77.638512        NaN
four   81.732061        NaN  93.702347        NaN <class 'pandas.core.frame.DataFrame'>

In [47]:
# 按照index降序
# 这是算着每行的总和进行降序
# - axis：0按照行名排序；1按照列名排序
# - ascending：默认True升序排列；False降序排列
# - inplace：默认False，否则排序之后的数据直接替换原来的数据
df.sort_index(axis=0, ascending=False)
df.sort_index(axis=1, ascending=False)

               d          c          b          a
one    86.509633  34.377420  11.297014  63.805662
two    48.403465  76.926601  52.779439  29.753325
three  27.286880  77.638512  91.026485  71.488561
four   37.688954  93.702347   4.492647  81.732061

In [40]:
#按照列降序
#先按b列降序，再按a列升序排序
df.sort_values(by=['b','a'],ascending=[False,True])

               a          b          c          d
three  71.488561  91.026485  77.638512  27.286880
two    29.753325  52.779439  76.926601  48.403465
one    63.805662  11.297014  34.377420  86.509633
four   81.732061   4.492647  93.702347  37.688954